export const AUTH_LOGIN = 'CADENCE.AUTH_LOGIN'
export const AUTH_LOGIN_FAIL = 'CADENCE.AUTH_LOGIN_FAIL'
export const AUTH_LOGIN_SUCCESS = 'CADENCE.AUTH_LOGIN_SUCCESS'
export const AUTH_LOGOUT = 'CADENCE.AUTH_LOGOUT'
