export const GET_SUMMARIES = 'CADENCE.GET_SUMMARIES'
export const GET_TOTALS_AND_TRENDS = 'CADENCE.GET_TOTALS_AND_TRENDS'
export const GET_TOP_TRENDINGS = 'CADENCE.GET_TOP_TRENDINGS'
export const GET_DOWNLOADS_BY_SOURCE = 'CADENCE.GET_DOWNLOADS_BY_SOURCE'
