export const GET_USER_PREFERENCE = 'CADENCE.GET_USER_PREFERENCE'
export const UPDATE_USER_PREFERENCE = 'CADENCE.UPDATE_USER_PREFERENCE'
export const GET_USER_SERIES = 'CADENCE.GET_USER_SERIES'
export const GET_USERS_LIST = 'CADENCE.GET_USERS_LIST'
