export const countryMatchArray = {
  'Bolivia, Plurinational State of': 'Bolivia',
  Bahamas: 'The Bahamas',
  'Brunei Darussalam': 'Brunei',
  'Cabo Verde': 'Cape Verde',
  'Congo, The Democratic Republic of the': 'Democratic Republic of the Congo',
  'Iran, Islamic Republic of': 'Iran',
  'Korea, Republic of': 'South Korea',
  "Lao People's Democratic Republic": 'Laos',
  'Micronesia, Federated States of': 'Federated States of Micronesia',
  'Moldova, Republic of': 'Moldova',
  'North Macedonia': 'Macedonia',
  'Russian Federation': 'Russia',
  Serbia: 'Republic of Serbia',
  'Taiwan, Province of China': 'Taiwan',
  'Tanzania, United Republic of': 'United Republic of Tanzania',
  'Timor-Leste': 'East Timor',
  'United States': 'United States of America',
  'Venezuela, Bolivarian Republic of': 'Venezuela',
  'Viet Nam': 'Vietnam',
  'Virgin Islands, U.S.': 'United States Virgin Islands'
}
